### ISSUE TITLE
Periodic saving doesnt save data if measurement is stopped

### ISSUE THREAD

**Issue by gasperkrivic** [ladisk/LDAQ#44]
When I was using periodic saving and stopped the measurement in visualization, the last chunk of the measurement did not get saved.

**Comment by gasperkrivic** [comment]
Check that periodic saving thread exits properly

**Comment by TKosir** [comment]
With updates to periodic saving data related to #39, this issue was eliminated as well. I've tested this behavior using simulated acquisitions and everything seems to be working. If issues still exist for some users I will reopen this issue.
