### ISSUE TITLE
periodic saving misses data

### ISSUE THREAD

**Issue by gasperkrivic** [ladisk/LDAQ#60]
![image](https://github.com/ladisk/LDAQ/assets/52493759/338c5600-004d-4215-af69-a9887e77efb1)

**Comment by TKosir** [comment]
here it might seem that are missing data in the middle, but actually we're missing data at the end and generated time vector is wrong. I will try to solve this issue soon.

**Comment by TKosir** [comment]
same bug as #44 .

**Comment by gasperkrivic** [comment]
I ran the measurement for 30 minutes, which should result in 54k data points, but only the last 11912 data points were saved. 

![image](https://github.com/ladisk/LDAQ/assets/52493759/92f4ce79-a021-4ff5-89d3-ce149925323f)

**Comment by TKosir** [comment]
I've found a bug related to the relative paths of files in which measurements are saved. I've solved the issue, now the periodic saving works for me. I've updated the master branch with the changes.
