### ISSUE TITLE
different temperature on image and average calculated

### ISSUE THREAD

**Issue by gasperkrivic** [ladisk/LDAQ#62]
![image](https://github.com/ladisk/LDAQ/assets/52493759/b5dbeb76-a977-499a-adb0-3c7c90b080c7)

**Comment by TKosir** [comment]
I suggest taking 1 frame, mask it and then compare the full masked array with value that comes out of average() function you're using.

**Comment by TKosir** [comment]
Virtual channels work, hovering with the mouse over a pixel can sometimes show values of some other pixel.

**Comment by TKosir** [comment]
found the issue and solved it, currently change is applied to dev branch, will merge with master soon.
